In [1]:
import sys 
print(sys.version)

3.5.2 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]

### `None` Object

None-রে আসলে ডাটাস্ট্রাকচারে ফেলা ঠিক হবে না। কিন্তু পাইথনে None এর ব্যবহার মূলত, অন্য সব ল্যাঙ্গুয়েজের NULL,nil ব্যবহার করার মতো। None এর ব্যবহার সাধারণত Array,List,Collections আইটেম আছে কিনা সেটা দেখা হয়। এক্ষেত্রে None কিভাবে হ্যান্ডেল করা হয় সেটা না দেখে আমরা দেখবো objectটি none কিনা। কোড লিখলে এমন দাঁড়াবে-

    for item in collection:
        if item is not None:
            process(item)
        else:
            pass

### Numeric Types

তিন ধরণের হয় 
    *  পূর্ণসংখ্যা (integers numbers) 
    *  দশমিক সংখ্যা(floating-points numbers) 
    *  জটিল সংখ্যা(complex numbers)

### Bool Types
Bool types, বুলিয়ান টাইপ্স আসলে ইন্টিজারস ক্লাসের সাবক্লাস। এর ভ্যালু শুধুমাত্র True অথবা False হতে পারে ।

In [3]:
True == 1

True

In [4]:
False < 1

True

In [5]:
(True + 1 )

2

In [6]:
isinstance(False,bool)

True

In [7]:
type(False)

bool

In [8]:
isinstance(True,int)

True

In [9]:
issubclass(bool,int)

True

### Integer type

In [10]:
int_value = 12345678
print(int_value, type(int_value))

12345678 <class 'int'>

In [11]:
# Hexadecimal integers
print(0xFF03) # 15*16**3 + 15*16**2 +0*16**1 +3*16**0
print(0XFF03)

65283
65283

In [12]:
# Octal integers
print(0o76543) # 7*8**4 + 6*8**3 + 5*8**2 + 4*8**1 + 3*8**0
print(0O76543)

32099
32099

In [13]:
# Binary integers
print(0b10010011) # 1*2**7 + 0*2**6 + 0*2**5 + 1*2**4 + 0*2**3 + 0*2**2 + 1*2**1 + 1*2**0
print(0B10010011)

147
147

In [14]:
# A number in base 6
int("3421", 6)

805

In [15]:
# Some integers
print(2**8)
print(2**32)
print(2**64)
print(2**65)
print(2**129)

256
4294967296
18446744073709551616
36893488147419103232
680564733841876926926749214863536422912

In [16]:
# Even very large integers can be represented in Python
2**(2**16)

2003529930406846464979072351560255750447825475569751419265016973710894059556311453089506130880933348101038234342907263181822949382118812668869506364761547029165041871916351587966347219442930927982084309104855990570159318959639524863372367203002916969592156108764948889254090805911457037675208500206671563702366126359747144807111774815880914135742720967190151836282560618091458852699826141425030123391108273603843767876449043205960379124490905707560314035076162562476031863793126484703743782954975613770981604614413308692118102485959152380195331030292162800160568670105651646750568038741529463842244845292537361442533614373729088303794601274724958414864915930647252015155693922628180691650796381064132275307267143998158508811292628901134237782705567421080070065283963322155077831214288551675554073345107213112427399562982719769150054883905223804357045848197956393157853510018992000024141963706813559840464039472194016069517690156119726982337890017641517190051133466306898140219383481435426387306539552969691388024158161859561100640362119796101859534802787167200122604642492385111393400464351623867567078745259464670903886547743483217897012764455529409092021959585751622973333576159552394885297579954028471943529913543763705986928913757153740001986394332464890052543106629669165243419174691389632476560289415199775477703138064781342309596190960654591300890188887588084733625956065444888501447335706058817090162108499714529568344061979690565469813631162053579369791403236328496233046421066136200220175787851857409162050489711781820400187282939943446186224328009837323764931814789848119452713007440220765680910376203999203492023906626264491909167985461515778839060397720759279378852241294301017458086862263369284725851403039615558564330385450688652213114813638408384778263790459607186876728509763471271988890680478243230394718650525660978150729861141430305816927924971409161059417185352275887504477592218301158780701975535722241400019548102005661773589781499532325208589753463547007786690406429016763808161740550405117670093673202804549339027992491867306539931640720492238474815280619166900933805732120816350707634351669869625020969023162859350071874190579161241536897514808261904847946571736601005892476655445840838334790544144817684255327207315586349347605137419779525190365032198020108764738368682531025183377533908861426184800374008082238104076468878471647552945326947661700424461063311238021134588694532200116564076327023074292426051582811070387018345324567635625951430032037432740780879056283663406965030844225855967039271869461158513793386475699748568670079823960604393478850861649260304945061743412365828352144806726676841807083754862211408236579802961200027441324438432402331257403545019352428776430880232850855886089962774458164680857875115807014743763867976955049991643998284357290415378143438847303484261903388841494031366139854257635577105335580206622185577060082551288893332226436281984838613239570676191409638533832374343758830859233722284644287996245605476932428998432652677378373173288063210753211238680604674708428051166488709084770291208161104912555598322366244868556651402684641209694982590565519216188104341226838996283071654868525536914850299539675503954938371853405900096187489473992880432496373165753803673586710175783994818471798498246948060532081996066183434012476096639519778021441199752546704080608499344178256285092726523709898651539462193004607364507926212975917698293892367015170992091531567814439791248475706237804600009918293321306880570046591458387208088016887445835557926258465124763087148566313528934166117490617526671492672176128330845273936469244582892571388877839056300482483799839692029222215486145902373478222682521639957440801727144146179559226175083889020074169926238300282286249284182671243405751424188569994272331606998712986882771820617214453142574944015066139463169197629181506579745526236191224848063890033669074365989226349564114665503062965960199720636202603521917776740668777463549375318899587866282125469797102065747232721372918144666659421872003474508942830911535189271114287108376159222380276605327823351661555149369375778466670145717971901227117812780450240026384758788339396817962950690798817121690686929538248529830023476068454114178139110648560236549754227497231007615131870024053910510913817843721791422528587432098524957878034683703337818421444017138688124249984418618129271198533315382567321870421530631197748535214670955334626336610864667332292409879849256691109516143618601548909740241913509623043612196128165950518666022030715613684732364660868905014263913906515063908199378852318365059897299125404479443425166774299659811849233151555272883274028352688442408752811283289980625912673699546247341543333500147231430612750390307397135252069338173843322950701049061867539433130784798015655130384758155685236218010419650255596181934986315913233036096461905990236112681196023441843363334594927631946101716652913823717182394299216272538461776065694542297877071383198817036964588689811863210976900355735884624464835706291453052757101278872027965364479724025405448132748391794128826423835171949197209797145936887537198729130831738033911016128547415377377715951728084111627597186384924222802373441925469991983672192131287035585307966942713416391033882754318613643490100943197409047331014476299861725424423355612237435715825933382804986243892498222780715951762757847109475119033482241412025182688713728193104253478196128440176479531505057110722974314569915223451643121848657575786528197564843508958384722923534559464521215831657751471298708225909292655638836651120681943836904116252668710044560243704200663709001941185557160472044643696932850060046928140507119069261393993902735534545567470314903886022024639948260501762431969305640666366626090207048887438898907498152865444381862917382901051820869936382661868303915273264581286782806601337500096593364625146091723180312930347877421234679118454791311109897794648216922505629399956793483801699157439700537542134485874586856047286751065423341893839099110586465595113646061055156838541217459801807133163612573079611168343863767667307354583494789788316330129240800836356825939157113130978030516441716682518346573675934198084958947940983292500086389778563494693212473426103062713745077286156922596628573857905533240641849018451328284632709269753830867308409142247659474439973348130810986399417379789657010687026734161967196591599588537834822988270125605842365589539690306474965584147981310997157542043256395776070485100881578291408250777738559790129129407309462785944505859412273194812753225152324801503466519048228961406646890305102510916237770448486230229488966711380555607956620732449373374027836767300203011615227008921843515652121379215748206859356920790214502277133099987729459596952817044582181956080965811702798062669891205061560742325686842271306295009864421853470810407128917646906550836129916694778023822502789667843489199409657361704586786242554006942516693979292624714524945408858422726153755260071904336329196375777502176005195800693847635789586878489536872122898557806826518192703632099480155874455575175312736471421295536494084385586615208012115079075068553344489258693283859653013272046970694571546959353658571788894862333292465202735853188533370948455403336565356988172582528918056635488363743793348411845580168331827676834646291995605513470039147876808640322629616641560667508153710646723108461964247537490553744805318226002710216400980584497526023035640038083472053149941172965736785066421400842696497103241919182121213206939769143923368374709228267738708132236680086924703491586840991153098315412063566123187504305467536983230827966457417620806593177265685841681837966106144963432544111706941700222657817358351259821080769101961052229263879745049019254311900620561906577452416191913187533984049343976823310298465893318373015809592522829206820862230332585280119266496314441316442773003237792274712330696417149945532261035475145631290668854345426869788447742981777493710117614651624183616680254815296335308490849943006763654806102940094693750609845588558043970485914449584445079978497045583550685408745163316464118083123079704389849190506587586425810738422420591191941674182490452700288263983057950057341711487031187142834184499153456702915280104485145176055306971441761368582384102787659324662689978418319620312262421177391477208004883578333569204533935953254564897028558589735505751235129536540502842081022785248776603574246366673148680279486052445782673626230852978265057114624846595914210278122788941448163994973881884622768244851622051817076722169863265701654316919742651230041757329904473537672536845792754365412826553581858046840069367718605020070547247548400805530424951854495267247261347318174742180078574693465447136036975884118029408039616746946288540679172138601225419503819704538417268006398820656328792839582708510919958839448297775647152026132871089526163417707151642899487953564854553553148754978134009964854498635824847690590033116961303766127923464323129706628411307427046202032013368350385425360313636763575212604707425311209233402837482949453104727418969287275572027615272268283376741393425652653283068469997597097750005560889932685025049212884068274139881631540456490350775871680074055685724021758685439053228133770707415830756269628316955687424060527726485853050611356384851965918968649596335568216975437621430778665934730450164822432964891270709898076676625671517269062058815549666382573829274182082278960684488222983394816670984039024283514306813767253460126007269262969468672750794346190439996618979611928750519442356402644303271737341591281496056168353988188569484045342311424613559925272330064881627466723523751234311893442118885085079358163848994487544756331689213869675574302737953785262542329024881047181939037220666894702204258836895840939998453560948869946833852579675161882159410981624918741813364726965123980677561947912557957446471427868624053750576104204267149366084980238274680575982591331006919941904651906531171908926077949119217946407355129633864523035673345588033313197080365457184791550432654899559705862888286866606618021882248602144999973122164138170653480175510438406624412822803616648904257377640956326482825258407669045608439490325290526337532316509087681336614242398309530806549661879381949120033919489494065132398816642080088395554942237096734840072642705701165089075196155370186264797456381187856175457113400473810762763014953309735174180655479112660938034311378532532883533352024934365979129341284854970946826329075830193072665337782559314331110963848053940859283988907796210479847919686876539987477095912788727475874439806779824968278272200926449944559380414608770641941810440758269805688038949654616587983904660587645341810289907194293021774519976104495043196841503455514044820928933378657363052830619990077748726922998608279053171691876578860908941817057993404890218441559791092676862796597583952483926734883634745651687016166240642424241228961118010615682342539392180052483454723779219911228595914191877491793823340010078128326506710281781396029120914720100947878752551263372884222353869490067927664511634758101193875319657242121476038284774774571704578610417385747911301908583877890152334343013005282797038580359815182929600305682612091950943737325454171056383887047528950563961029843641360935641632589408137981511693338619797339821670761004607980096016024823096943043806956620123213650140549586250615282588033022908385812478469315720323233601899469437647726721879376826431828382603564520699468630216048874528424363593558622333506235945002890558581611275341783750455936126130852640828051213873177490200249552738734585956405160830583053770732533971552620444705429573538361113677523169972740292941674204423248113875075631319078272188864053374694213842169928862940479635305150560788126366206497231257579019598873041195626227343728900516561111094111745277965482790471250581999077498063821559376885546498822938985408291325129076478386322494781016753491693489288104203015610283386143827378160946341335383578340765314321417150655877547820252454780657301342277470616744241968952613164274104695474621483756288299771804186785084546965619150908695874251184435837306590951460980451247409411373899927822492983367796011015387096129749705566301637307202750734759922943792393824427421186158236161317886392553095117188421298508307238259729144142251579403883011359083331651858234967221259621812507058113759495525022747274674369887131926670769299199084467161228738858457584622726573330753735572823951616964175198675012681745429323738294143824814377139861906716657572945807804820559511881687188075212971832636442155336787751274766940790117057509819575084563565217389544179875074523854455200133572033332379895074393905312918212255259833790909463630202185353848854825062897715616963860712382771725621313460549401770413581731931763370136332252819127547191443450920711848838366818174263342949611870091503049165339464763717766439120798347494627397822171502090670190302469762151278521956142070806461631373236517853976292092025500288962012970141379640038055734949269073535145961208674796547733692958773628635660143767964038430796864138563447801328261284589184898528048048844180821639423974014362903481665458114454366460032490618763039502356402044530748210241366895196644221339200757479128683805175150634662569391937740283512075666260829890491877287833852178522792045771846965855278790447562192663992008409302075673925363735628390829817577902153202106409617373283598494066652141198183810884515459772895164572131897797907491941013148368544639616904607030107596818933741217575988165127000761262789169510406315857637534787420070222051070891257612361658026806815858499852631465878086616800733264676830206391697203064894405628195406190685242003053463156621891327309069687353181641094514288036605995220248248886711554429104721929134248346438705368508648749099178812670565665387191049721820042371492740164460943459845392536706132210616533085662021188968234005752675486101476993688738209584552211571923479686888160853631615862880150395949418529489227074410828207169303387818084936204018255222271010985653444817207470756019245915599431072949578197878590578940052540122867517142511184356437184053563024181225473266093302710397968091064939272722683035410467632591355279683837705019855234621222858410557119921731717969804339317707750755627056047831779844447637560254637033369247114220815519973691371975163241302748712199863404548248524570118553342675264715978310731245663429805221455494156252724028915333354349341217862037007260315279870771872491234494477147909520734761385425485311552773301030342476835865496093722324007154518129732692081058424090557725645803681462234493189708138897143299831347617799679712453782310703739151473878692119187566700319321281896803322696594459286210607438827416919465162267632540665070881071030394178860564893769816734159025925194611823642945652669372203155504700213598846292758012527715422016629954863130324912311029627923723899766416803497141226527931907636326136814145516376656559839788489381733082668779901962886932296597379951931621187215455287394170243669885593888793316744533363119541518404088283815193421234122820030950313341050704760159987985472529190665222479319715440331794836837373220821885773341623856441380700541913530245943913502554531886454796252260251762928374330465102361057583514550739443339610216229675461415781127197001738611494279501411253280621254775810512972088465263158094806633687670147310733540717710876615935856814098212967730759197382973441445256688770855324570888958320993823432102718224114763732791357568615421252849657903335093152776925505845644010552192644505312073756287744998163646332835816140330175813967359427327690448920361880386754955751806890058532927201493923500525845146706982628548257883267398735220457228239290207144822219885587102896991935873074277815159757620764023951243860202032596596250212578349957710085626386118233813318509014686577064010676278617583772772895892746039403930337271873850536912957126715066896688493880885142943609962012966759079225082275313812849851526902931700263136328942095797577959327635531162066753488651317323872438748063513314512644889967589828812925480076425186586490241111127301357197181381602583178506932244007998656635371544088454866393181708395735780799059730839094881804060935959190907473960904410150516321749681412100765719177483767355751000733616922386537429079457803200042337452807566153042929014495780629634138383551783599764708851349004856973697965238695845994595592090709058956891451141412684505462117945026611750166928260250950770778211950432617383223562437601776799362796099368975191394965033358507155418436456852616674243688920371037495328425927131610537834980740739158633817967658425258036737206469351248652238481341663808061505704829059890696451936440018597120425723007316410009916987524260377362177763430621616744884930810929901009517974541564251204822086714586849255132444266777127863728211331536224301091824391243380214046242223349153559516890816288487989988273630445372432174280215755777967021666317047969728172483392841015642274507271779269399929740308072770395013581545142494049026536105825409373114653104943382484379718606937214444600826798002471229489405761853892203425608302697052876621377373594394224114707074072902725461307358541745691419446487624357682397065703184168467540733466346293673983620004041400714054277632480132742202685393698869787607009590048684650626771363070979821006557285101306601010780633743344773073478653881742681230743766066643312775356466578603715192922768440458273283243808212841218776132042460464900801054731426749260826922155637405486241717031027919996942645620955619816454547662045022411449404749349832206807191352767986747813458203859570413466177937228534940031631599544093684089572533438702986717829770373332806801764639502090023941931499115009105276821119510999063166150311585582835582607179410052528583611369961303442790173811787412061288182062023263849861515656451230047792967563618345768105043341769543067538041113928553792529241347339481050532025708728186307291158911335942014761872664291564036371927602306283840650425441742335464549987055318726887926424102147363698625463747159744354943443899730051742525110877357886390946812096673428152585919924857640488055071329814299359911463239919113959926752576359007446572810191805841807342227734721397723218231771716916400108826112549093361186780575722391018186168549108500885272274374212086524852372456248697662245384819298671129452945515497030585919307198497105414181636968976131126744027009648667545934567059936995464500558921628047976365686133316563907395703272034389175415267500915011198856872708848195531676931681272892143031376818016445477367518353497857924276463354162433601125960252109501612264110346083465648235597934274056868849224458745493776752120324703803035491157544831295275891939893680876327685438769557694881422844311998595700727521393176837831770339130423060958999137314684569010422095161967070506420256733873446115655276175992727151877660010238944760539789516945708802728736225121076224091810066700883474737605156285533943565843756271241244457651663064085939507947550920463932245202535463634444791755661725962187199279186575490857852950012840229035061514937310107009446151011613712423761426722541732055959202782129325725947146417224977321316381845326555279604270541871496236585252458648933254145062642337885651464670604298564781968461593663288954299780722542264790400616019751975007460545150060291806638271497016110987951336633771378434416194053121445291855180136575558667615019373029691932076120009255065081583275508499340768797252369987023567931026804136745718956641431852679054717169962990363015545645090044802789055701968328313630718997699153166679208958768572290600915472919636381673596673959975710326015571920237348580521128117458610065152598883843114511894880552129145775699146577530041384717124577965048175856395072895337539755822087777506072339445587895905719156736

In [17]:

print(3 << 4)  # shift left (int only)
print(33 >> 4) # shift right (int only)
print(3 & 4)   # bitwise and (int only)
print(3 | 4)   # bitwise or (int only)
print(3 ^ 4)   # bitwise xor (int only)
print(~ 3)     # bitwise not (int only)

48
2
0
7
7
-4

### Floating Point Number 

floating point number গুলা ২ ভাবে দেখানো যায়-

In [19]:
a = 4.732
b = 123e2
print(a,type(a))
print(b,type(b))     # 12300; "123e2" means "123 times 10**2"

4.732 <class 'float'>
12300.0 <class 'float'>

In [20]:
print(456E-4)    # 0.0456; "456e-4" means "456 times 10**(-4)"
print(-.7436e3)  # -743.6
print(1476.3e20) # 1.4763*10**23

0.0456
-743.6
1.4763e+23

In [21]:
-12345.6e78

-1.23456e+82

In [22]:

sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

In [23]:
-1.23456e310

-inf

In [24]:
float('Inf') / float('-inf')

nan

In [25]:
inf = float('inf')
inf-inf, inf/inf

(nan, nan)

nan এর মানে হইলো "not a number"। প্রতিটা nan ই অসীম । কিন্তু কোন nan ই আরেকটা nan এর সমান হবে না

In [26]:

-1.23456e310 == -inf

True

In [27]:
inf == inf+2 == float('inf')

True

In [28]:
inf is inf+2

False

In [30]:
inf-inf == inf/inf

False

In [31]:
float('nan') == float('nan')

False

In [32]:
b = sum([1/7]*7) # equivalent to "1/7 + 1/7 + 1/7 + 1/7 + 1/7 + 1/7 + 1/7"
print("1/7 + 1/7 + 1/7 + 1/7 + 1/7 + 1/7 + 1/7 != 1.0")
print(b, "!=", 1.0)

1/7 + 1/7 + 1/7 + 1/7 + 1/7 + 1/7 + 1/7 != 1.0
0.9999999999999998 != 1.0

In [33]:
# Associativity can produce rounding errors
a = (0.1 + 0.2) + 0.3
b = 0.1 + (0.2 + 0.3)
print(a, b)

0.6000000000000001 0.6

In [34]:
# Or overflows depending on associativity
a = (1e307*100) / 100
b = 1e307 * (100/100)
print(a, b)

inf 1e+307

In [35]:
delta = 0.0001   # Set our tolerance delta
δ = delta 
abs(3.14159265 - 3.1415) < δ

True

In [36]:
type(δ)

float

#### Type Casting

In [37]:
1.0/0

ZeroDivisionError: float division by zero

In [38]:
1/0

ZeroDivisionError: division by zero

In [40]:
print(1/5)

0.2

In [41]:
# Types of division (different from Python 2.x)
print(2/3)
print(2//3)
print(2.0//3.0)

0.6666666666666666
0
0.0

In [42]:
denominators = [3, 4, 6, 0, 3]
for d in denominators:
    print("d = %d" % d)
    print(7/d)

d = 3
2.3333333333333335
d = 4
1.75
d = 6
1.1666666666666667
d = 0

ZeroDivisionError: division by zero

In [43]:
denominators = [3, 4, 6, 0, 3]
for d in denominators:
    print("d = %d" % d)
    try:
        print(7/d)
    except ZeroDivisionError:
        print("Attempt to divide by zero")

d = 3
2.3333333333333335
d = 4
1.75
d = 6
1.1666666666666667
d = 0
Attempt to divide by zero
d = 3
2.3333333333333335

### Complex type(complex number)

In [44]:
# Complex numbers
print(4.56e-3+7.5e1j)
complex_one = 1 + 0j 
print(complex_one == 1.0)
print(complex_one is 1.0)
type(complex_one)

(0.00456+75j)
True
False

complex

int কিংবা float নাম্বার এর সাথে complex Type এর যদি কোন arithmatic operation হয় তাহলে সেটা type casting হয়ে complex type object এ পরিবর্তন হবে

In [45]:
a = 3  # Try replacing with various integer of floating-point values
print(type(a))
a += complex_one # casts resulting value to a complex value
print(a, type(a))

<class 'int'>
(4+0j) <class 'complex'>

In [46]:
x, y = 3, 4.0
print("x is of type {} and y is of type {}".format(type(x), type(y)))
# cast to "higher type" as needed
print("x + y == {} is of type {}".format(x+y, type(x+y)))

x is of type <class 'int'> and y is of type <class 'float'>
x + y == 7.0 is of type <class 'float'>

In [47]:
x, y = complex(3,4), 4.0
print("x is of type {} and y is of type {}".format(type(x), type(y)))
# cast to "higher type" as needed
print("x * y == {} is of type {}".format(x*y, type(x*y)))

x is of type <class 'complex'> and y is of type <class 'float'>
x * y == (12+16j) is of type <class 'complex'>

In [48]:
1+1j < -1-.5j

TypeError: unorderable types: complex() < complex()

In [50]:
3+4j < 4+3j

TypeError: unorderable types: complex() < complex()

In [51]:
1+0j == 1, 2+0j == 2, 1 < 2

(True, True, True)

In [52]:
z = -1.43e-1+0.5e2j
print("real(z) = {:.3e}\nimag(z) = {:.3e}".format(z.real, z.imag))
print("conjugate(z) =", z.conjugate())

real(z) = -1.430e-01
imag(z) = 5.000e+01
conjugate(z) = (-0.143-50j)

In [53]:
pow = __builtins__.pow
print(3 + 4)          # addition
print(3 - 4)          # subtraction
print(3 * 4)          # multiplication
print(3 / 4)          # "true division"
print(3 // 4)         # floor division
print(13 % 4)         # modulo
print(3 ** 4)         # power
print(abs(3-4))       # absolute value
print(pow(3.0j,4))    # expect 81+0j
print(pow(3, 4, 5))   # power with optional modulo: (3**4) % 5
print(divmod(3, 4))   # division with remainder
print(int(3.14))      # convert to an int
print(float(3))       # convert to a float

7
-1
12
0.75
0
1
81
1
(81+0j)
1
(0, 3)
3
3.0

### str (string) type

In [54]:
a = 'a string'
print(a, type(a))

a string <class 'str'>

In [55]:
string_1 = 'Single quotes as delimiters permit "double" quotes inside.'
string_2 = "Double quotes as delimiters don't have problems with 'single' quotes inside."
string_3 = '''
Triple (single) quotes don't have problems with 'single' or "double" quotes
inside. They don't even have problems with line breaks!
'''
print(string_1)
print(string_2)
print(string_3)

Single quotes as delimiters permit "double" quotes inside.
Double quotes as delimiters don't have problems with 'single' quotes inside.

Triple (single) quotes don't have problems with 'single' or "double" quotes
inside. They don't even have problems with line breaks!

In [56]:
empty_str = ''
string_1 = 'Single quotes as delimiters permit \'escaped single\' quotes inside.'
string_2 = "Double quotes as delimiters \"escaped double\" quotes inside."
string_3 = '''Other escaped characters include the literal backslash \\,
Unicode characters with hex values like \\u00CC == \u00CC,'''
string_4 = 'the\ttab character \\t &\nthe line feed \\n.'
print('empty_str = %r' % empty_str)
print(string_1)
print(string_2)
print(string_3,string_4)

empty_str = ''
Single quotes as delimiters permit 'escaped single' quotes inside.
Double quotes as delimiters "escaped double" quotes inside.
Other escaped characters include the literal backslash \,
Unicode characters with hex values like \u00CC == Ì, the	tab character \t &
the line feed \n.

In [57]:
print("Unicode charcters may be entered by name: \N{GREEK SMALL LETTER DELTA}. ",
      "And also by codepoint: \u03B4")

Unicode charcters may be entered by name: δ.  And also by codepoint: δ

In [58]:
print("Strings can contain either literal non-ASCII characters",
      "Say in Русский.  Or they can contain escapes to codepoints",
      "such as \u0420\u0443\u0441\u0441\u043a\u0438\u0439")

Strings can contain either literal non-ASCII characters Say in Русский.  Or they can contain escapes to codepoints such as Русский

In [59]:
import unicodedata
unicodedata.lookup("GREEK SMALL LETTER DELTA")

'δ'

In [60]:
hex(ord("δ"))

'0x3b4'

In [61]:
unicodedata.name("δ")

'GREEK SMALL LETTER DELTA'

In [62]:
old_s = 'Mary had a little lamb\nIts fleece was white as snow\nAnd everywhere that Mary went\nThe lamb was sure to go.'
print(old_s)

Mary had a little lamb
Its fleece was white as snow
And everywhere that Mary went
The lamb was sure to go.

In [63]:
new_s = """Mary had a little lamb
Its fleece was white as snow
And everywhere that Mary went
The lamb was sure to go."""
print(new_s)

Mary had a little lamb
Its fleece was white as snow
And everywhere that Mary went
The lamb was sure to go.

In [64]:
# Check whether the strings new_s and old_s are identical in every way.
print(new_s == old_s) 
new_s is old_s

True

False

In [65]:
s = "Ain't it a shame?!"  # Single quote in double quotes
s

"Ain't it a shame?!"

In [66]:
s = 'Ain\'t it a shame?!' # Another example of escaping characters within strings
print(s)

Ain't it a shame?!

In [67]:
s = """He said "Ain't that a shame"!""" # Triple quotes to include both single/double
print(s)

He said "Ain't that a shame"!

In [68]:
print('He said "Hi" to me')

He said "Hi" to me

In [69]:
print("He said \"Hi\" to me")

He said "Hi" to me

### String methods


capitalize	casefold	center	count
encode	endswith	expandtabs	find
format	format_map	index	isalnum
isalpha	isdecimal	isdigit	isidentifier
islower	isnumeric	isprintable	isspace
istitle	isupper	join	ljust
lower	lstrip	maketrans	partition
replace	rfind	rindex	rjust
rpartition	rsplit	rstrip	split
splitlines	strip	swapcase	title
translate	upper	zfill

In [70]:
haiku = """
    an aging willow
    its image unsteady
    in the flowing stream
"""
print(haiku)

    an aging willow
    its image unsteady
    in the flowing stream

In [72]:
haiku.count('i')

6

In [73]:
haiku.count('in')

3

In [74]:
haiku.split()

['an',
 'aging',
 'willow',
 'its',
 'image',
 'unsteady',
 'in',
 'the',
 'flowing',
 'stream']

In [75]:
haiku.count('x') # returns 0 because 'x' is not a substring of haiku

0

In [76]:
print(haiku.strip()) # Removes leading/trailing whitespace (but not internal whitespace)

an aging willow
    its image unsteady
    in the flowing stream

In [77]:
# Splits string haiku on line feed characters; returns a *list*
lines = haiku.split('\n')
lines

['',
 '    an aging willow',
 '    its image unsteady',
 '    in the flowing stream',
 '']

In [78]:
# We're going to jump ahead slightly in this example, i.e., using list conprehension
# The following removes empty lines as well as trailing whitespace
[line.strip() for line in haiku.split('\n') if line]

['an aging willow', 'its image unsteady', 'in the flowing stream']

In [79]:

# joining pieces back together
print("\n".join([line.strip() for line in haiku.split('\n') if line]))

an aging willow
its image unsteady
in the flowing stream

In [80]:
print(haiku.upper()) # Convert to upper case, return a new string
print(haiku)

    AN AGING WILLOW
    ITS IMAGE UNSTEADY
    IN THE FLOWING STREAM


    an aging willow
    its image unsteady
    in the flowing stream

In [81]:

# replaces a source substring with target substring, return as new string
print(haiku.replace('unsteady','wavering'))

    an aging willow
    its image wavering
    in the flowing stream

In [82]:

# nothing happens with the source substring not found
print(haiku.replace('uneasy','wavering')) 

'uneasy' in haiku # Should evaluate to False

'unsteady' in haiku

    an aging willow
    its image unsteady
    in the flowing stream

True

In [83]:

haiku.endswith('stream') # Whoops, need to strip the whitespace...

False

In [84]:

haiku.rstrip().endswith('stream') # This is what we expected...

True

In [85]:

# Another jump ahead to map().  This is another way of iterating implicitly
lines = map(str.strip, haiku.split('\n'))
[x for x in lines if x.endswith(('willow','stream'))]

['an aging willow', 'in the flowing stream']

In [86]:

haiku.isalpha() # Only True when all characters are alphanumeric

False

In [87]:
"David".isalpha() # Should be True

True

In [88]:

haiku.isdigit()

False

In [89]:
"12345".isdigit()

True

In [90]:


# This asks "are all the *letters* lowercase?", 
# not "are all the characters lowercase letters?
haiku.islower()

True

In [92]:

"abc123#$%^&".islower()

True

In [93]:

# However, there must also *be* some letters for this to be true
"12345".islower()

False

In [94]:

help(str.islower)

Help on method_descriptor:

islower(...)
    S.islower() -> bool

    Return True if all cased characters in S are lowercase and there is
    at least one cased character in S, False otherwise.

In [95]:

haiku.isupper()

False

In [96]:

# Converts string haiku into a list of words
# ... more specifically, divide the string around any sequence of whitespace
words = haiku.split() 
words

['an',
 'aging',
 'willow',
 'its',
 'image',
 'unsteady',
 'in',
 'the',
 'flowing',
 'stream']

In [97]:

print(words)
"__".join(words)

"_".join(haiku) # Treats string haiku as list of letters; joins all with '_'

['an', 'aging', 'willow', 'its', 'image', 'unsteady', 'in', 'the', 'flowing', 'stream']

'\n_ _ _ _ _a_n_ _a_g_i_n_g_ _w_i_l_l_o_w_\n_ _ _ _ _i_t_s_ _i_m_a_g_e_ _u_n_s_t_e_a_d_y_\n_ _ _ _ _i_n_ _t_h_e_ _f_l_o_w_i_n_g_ _s_t_r_e_a_m_\n'

In [98]:

prefixes = ('Ti', 'Da', 'Le')
"David".startswith(prefixes)

True

In [99]:
# Replaces line-feed with empty strings; puts all on one line
print(haiku.replace('\n',''))
# split into substrings on 'w'; returns list
haiku.replace('\n','').split('w')

    an aging willow    its image unsteady    in the flowing stream

['    an aging ', 'illo', '    its image unsteady    in the flo', 'ing stream']

In [100]:


# Returns leading index of first occurrence of 'aging' inside 'haiku'
haiku.find('aging')

8

In [101]:

# haiku.find(substring) returns -1 if the substring is not found
print(haiku.find('old'))

-1

In [102]:

help(str.find)

Help on method_descriptor:

find(...)
    S.find(sub[, start[, end]]) -> int

    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.

    Return -1 on failure.

In [103]:

# also str.rindex() exists, and behaves as expected
haiku.rfind('st'), haiku.find('st')

(63, 37)

In [104]:

# haiku.index is like haiku.find() with different error-handling bahaviour
haiku.index('aging')

8

In [105]:

haiku.index('old') # ValueError because 'old' not substring of haiku

ValueError: substring not found

In [106]:

haiku[0], haiku[10]

('\n', 'i')

In [107]:

haiku[:8]

'\n    an '

In [108]:

haiku[8:]

'aging willow\n    its image unsteady\n    in the flowing stream\n'

In [109]:

haiku[8:20]

'aging willow'

In [110]:

haiku[8:20] + haiku[20:30] == haiku[8:30]

True

In [111]:

haiku[-1]

'\n'

In [112]:

haiku[-20:-10]

' the flowi'

#### pythonic way to catch error

In [113]:
# Even more Pythonic to catch only the exception we know how to deal with
try:
    pos = haiku.index('old')
    print(haiku[pos:])
except ValueError as e: # In this version, we flag the particular exception
    # This except block executes only with a ValueError.
    print("Not found")

Not found

### String Indexing

String manipulate করার জন্য string indexing এবং string slicing অনেক গুরুত্বপূর্ণ। 
    * indexing শুরু হয় 0 থেকে বামদিক থেকে । 
    * আমরা যদি নেগেটিভ indices(-)দিয়ে কোন কিছু দেখতে যাই তাইলে সেটা array এর শেষ দিক থেকে শুরু হবে। 
    * আর যদি index এর থেকে বড় কোন সংখ্যা দিই, তাইলে সেটা IndexError খাবে

In [114]:
s = "My name is Akaimma"
print(s[11])  # Indexed from zero, so s[11] is the 12th character,; expect 'D'
print(s[-3])  # expect 'm'
print(len(s)) # Prints the length of the string

A
m
18

In [115]:
print(s[20]) # expecting an error

IndexError: string index out of range

#### Immutibility of `str` type

পাইথনে str টাইপ অবজেক্টকে immutible বলা হয়। এর মানে হচ্ছে, একবার যদি আমরা কোন str টাইপ ভেরিয়েবলরে এসাইন করি তাইলে সেটা আর চেঞ্জ করা যাবে না। str এর মতো আর কিছু immutible টাইপ অবজেক্ট আমরা সামনে দেখতে পারবো

In [116]:
print(s)
# This assignment works; s[4] on the right-hand sice of the assignment operator
c3 = s[3]
c3

My name is Akaimma

'n'

In [117]:
s[3] = 'g' # This raises an exception (TypeError)

TypeError: 'str' object does not support item assignment

In [118]:
print(s)
# Slicing: pull out char 4 up to (but *not* including) char 9 from string s
print(s[4:9])

My name is Akaimma
ame i

In [119]:
s[11:]

'Akaimma'

In [120]:
s[:11]

'My name is '

In [121]:
s[11:] + s[:11]

'AkaimmaMy name is '

In [122]:
s[-5]

'a'

In [123]:
s[-5:]

'aimma'

In [124]:
s[-5:-3]

'ai'

In [128]:
s[1:10:5]

'ye'

In [129]:
s[15:8:-2]

'maAs'

In [130]:
s[3:7] + s[7:10]

'name is'

#### String Conversion and format

In [131]:
print(float("3.14"),int(-8))

3.14 -8

In [132]:
a = str(42.5)
print(a)

42.5

In [133]:

from math import pi
print("Pi is about %d, in %s" % (pi, "Indiana"))
"For rough use, we often just use %0.4f" % pi

Pi is about 3, in Indiana

'For rough use, we often just use 3.1416'

In [134]:
"For rough use, we often just use %0.7f" % pi

'For rough use, we often just use 3.1415927'

In [135]:
"Better precision is %.17f" % pi

'Better precision is 3.14159265358979312'

In [136]:
"Past 17 digits, floating point precision is meaningless: %.30f" % pi

'Past 17 digits, floating point precision is meaningless: 3.141592653589793115997963468544'

In [137]:
"Octal %o; Decimal %i; HEX %X; hex %x; Octal w/ marker %#o; Hex w/ marker %#X" % (
       13,         13,     13,     13,                 13,                13)

'Octal 15; Decimal 13; HEX D; hex d; Octal w/ marker 0o15; Hex w/ marker 0XD'

In [138]:
"Explicit signs %+d, %+d" % (-13, 13)

'Explicit signs -13, +13'

In [140]:
"Zero padded ints %+06d, %+06d" % (-13, 13)

'Zero padded ints -00013, +00013'

In [141]:
"Space padded ints %6d, %6d" % (-13, 13)

'Space padded ints    -13,     13'

In [142]:
"A scientific notation format %.3e using 'e'" % 1234567890

"A scientific notation format 1.235e+09 using 'e'"

In [143]:
# Define a tuple of numeric values, say dollar amounts.
expenses = (1234.5678, 9900000.1, 83, .02)
for n, item in enumerate(expenses):
    print("Purchase %d:\t$%.2f" % (n+1, item))

Purchase 1:	$1234.57
Purchase 2:	$9900000.10
Purchase 3:	$83.00
Purchase 4:	$0.02

In [144]:
format_string = "Purchase {}:\t${:>13,.2f}" # Format string using new format mini-language
for n, item in enumerate(expenses):
    print(format_string.format(n+1, item))

Purchase 1:	$     1,234.57
Purchase 2:	$ 9,900,000.10
Purchase 3:	$        83.00
Purchase 4:	$         0.02

In [145]:
format_string = "Purchase {}:\t{:>14}"
for n, item in enumerate(expenses):
    amount = "${:,.2f}".format(item)
    print(format_string.format(n+1, amount))

Purchase 1:	     $1,234.57
Purchase 2:	 $9,900,000.10
Purchase 3:	        $83.00
Purchase 4:	         $0.02

#### Details on the str.format() mini-language

https://docs.python.org/3.4/library/string.html#formatstrings

In [147]:
# parameters can be out of order...
print("The capital of {1:s} is {2:s}, a {0:s} city".format(
                      "Badass", "Bangladesh", "Dhaka", "Shylet"))

The capital of Bangladesh is Dhaka, a Badass city

In [148]:
# Using keyword arguments to specify values to format
print("The capital of {country} is {capital}".format(
                      capital="Dhaka", country="Bangladesh", other="Barisal"))

The capital of Bangladesh is Dhaka

## Data Structures

<ul>
  <li>tuple</li>
  <li>list</li>
  <li>dict</li>
  <li>set</li>
</ul>

### tuple 

বৈশিষ্ট্যঃ 
<ul>
  <li>কমা সেপারেটেড</li>
  <li> সাধারণত"( )" দিয়ে আটকানো</li>
  <li>heterogeneous</li>
  <li>immutable</li>
  <li>ফাকা tuple বলতে " ( )"ই বুঝায় </li>
  <li>যে tuple-এ একটা মাত্র আইটেম আছে সেটারে (a,) এইভাবে লিখতে হবে </li>
  <li>immutable</li>
</ul>

In [150]:
# Some special syntax issues
empty_tup = ()              # Empty tuple
singleton_tup = ('Foo',)    # One-item tuple (comma required)
no_parens = "this", "that"  # Parentheses sometimes optional
print('empty_tup == %s has length %d.' % (empty_tup, len(empty_tup)))
print(singleton_tup)
print(no_parens)

empty_tup == () has length 0.
('Foo',)
('this', 'that')

In [151]:
my_tup = (4, 'a', 'giraffe', 3-4j)
print(my_tup)
print(type(my_tup))
print(my_tup[2:])

(4, 'a', 'giraffe', (3-4j))
<class 'tuple'>
('giraffe', (3-4j))

In [152]:
my_tup[4]

IndexError: tuple index out of range

In [153]:
# Multiple assignments equivalent to following three individual assignments.
# x = 3
# y = 4.7
# z = "My dog"
x, y, z = 3, 4.7, "My dog"  # We could write '(x, y, z) = (3, 4.7, "My dog")' instead
print('x=%d, y=%3.1f, z=%s' % (x,y,z))
my_tup = x, y, z
print('x=%d, y=%3.1f, z=%s' % my_tup)

x=3, y=4.7, z=My dog
x=3, y=4.7, z=My dog

In [154]:
print("x={:d}, y={:3.1f}, z={:s}".format(x, y, z))
print("x={:d}, y={:3.1f}, z={:s}".format(*my_tup))
print("x={2:d}, y={1:3.1f}, z={0:s}".format(z, y, x))

x=3, y=4.7, z=My dog
x=3, y=4.7, z=My dog
x=3, y=4.7, z=My dog

In [155]:
a,b,c = range(2,5) # tuple unpacking the range object
print('a=%d, b=%d, c=%d' % (a,b,c))

a=2, b=3, c=4

In [157]:
a, b, c = range(2,7)

ValueError: too many values to unpack (expected 3)

In [159]:
[a, b, c] = [1, 2, 3]

In [160]:
print(a, b)
a, b = b, a # Pythonic idiom for swapping variables by tuple assignment
print(a, b)

1 2
2 1

In [161]:
a, b, c = 4, 5, 6    # Tuple on right is "unpacked" into vars on right
print(a, b, c)

4 5 6

In [162]:
a, b, *c = range(10)
print('a=%s, b=%s, c=%s' % (a, b, c))

a=0, b=1, c=[2, 3, 4, 5, 6, 7, 8, 9]

In [163]:
a, *b, c = range(10)
print('a=%s, b=%s, c=%s' % (a, b, c))

a=0, b=[1, 2, 3, 4, 5, 6, 7, 8], c=9

In [164]:
*a, b, c = range(10)
a, b, c

([0, 1, 2, 3, 4, 5, 6, 7], 8, 9)

In [167]:
*a, b, a = range(12)
a, b

(11, 10)

In [168]:
a, *b, *c, d = range(100)

SyntaxError: two starred expressions in assignment (<ipython-input-168-6fd8d9f628b5>, line 1)

In [169]:
# Splitting the middle would be ambiguous, but you could do it explicitly
a, *b, c = range(30)
b1, b2 = b[:10], b[10:]
a, b1, b2, c

(0,
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
 29)

In [170]:
my_tup = (1,2,3)
try:
    my_tup[1] = 33
except TypeError:
    print("Trying to assign to immutable thing")

Trying to assign to immutable thing

In [171]:
tuple(reversed(my_tup)) # using builtin function reversed

(3, 2, 1)

In [172]:
reversed(my_tup), my_tup

(<reversed at 0x104a69c88>, (1, 2, 3))

Tuple এর মেথড ২ টা - count, index

In [173]:
my_tup = (4, 'a', 'giraffe', 3-4j)
print(my_tup)
my_tup.index('giraffe')

(4, 'a', 'giraffe', (3-4j))

2

In [175]:
my_tup.index(2)

ValueError: tuple.index(x): x not in tuple

In [176]:
letters = ('aaa', 'bbb', 'ccc')
letters.index('bbb')

1

In [177]:
tup2 = tuple("Mary had a little lamb")
print(tup2)
tup2.count('a')

('M', 'a', 'r', 'y', ' ', 'h', 'a', 'd', ' ', 'a', ' ', 'l', 'i', 't', 't', 'l', 'e', ' ', 'l', 'a', 'm', 'b')

4

In [178]:
x = (1,2,"A") + (4,5,6)
y = (1,2,"A") * 3
print(x)
print(y)

(1, 2, 'A', 4, 5, 6)
(1, 2, 'A', 1, 2, 'A', 1, 2, 'A')

In [179]:
tup10 = tuple(range(10))
newtup = tup10[:5] + ('five',) + tup10[6:]
newtup

(0, 1, 2, 3, 4, 'five', 6, 7, 8, 9)

### list

বৈশিষ্ট্যঃ 
<ul>
  <li>পাইথন লিস্ট হচ্ছে, কমা সেপারেটেড পাইথন অবজেক্টগুলার রেফেরেন্স Array</li>
  <li>কমা সেপারেটেড</li>
  <li> সাধারণত"[ ]" দিয়ে আটকানো</li>
  <li>heterogeneous</li>
  <li>ফাকা tuple বলতে "[ ]"ই বুঝায় </li>
  <li>+,* অপারেটর গুলা tuple,str এর মতোই ব্যবহার করবে </li>
  <li>mutable</li>
  <li>homogeneous arrays of uniform data type হ্যান্ডেল করার জন্য numpy ব্যবহার করা হয়</li>
  <li>tuple এবং lists এর মধ্যে পার্থক্য হইলো,tuple ব্যবহার করা হয় মূলত collections of associated information রেকর্ড করে রাখার জন্য। অন্য দিকে আইটেম লিস্ট হচ্ছে, একইরকম আচরণ করবে কিংবা একি রকম ব্যবহার পাবে এরকম লিস্ট </li>
</ul>

In [180]:
empty_list = []
print('empty_list = %s' % empty_list)
my_list = [4, 'a', 'giraffe', 3-4j]
print(my_list)
print(type(my_list))
print(my_list[2:])

empty_list = []
[4, 'a', 'giraffe', (3-4j)]
<class 'list'>
['giraffe', (3-4j)]

##### list এর মেথড অনেকগুলা, কিন্তু str এর চেয়ে কম

<ul>
<li>append</li>
<li>clear</li>
<li>copy</li>
<li>count</li>
<li>extend</li>
<li>index</li>
<li>insert</li>
<li>pop</li><li>remove</li>
<li>reverse</li><li>sort</li>

</ul>

In [183]:
fruit_list = ['banana','apple','mango','canteloupe']
print('Initial: fruit_list = %s' % fruit_list)

Initial: fruit_list = ['banana', 'apple', 'mango', 'canteloupe']

In [185]:
# Common mutation of a list: appending elements
fruit_list.append("guava")
print('After appending: fruit_list = %s' % fruit_list)

After appending: fruit_list = ['banana', 'apple', 'mango', 'canteloupe', 'guava']

In [186]:
# Related but different mutation: extending a list with elements from another list
fruit_list.extend(['pineapple','coconut','pear'])
print('After extending: fruit_list = %s' % fruit_list)

After extending: fruit_list = ['banana', 'apple', 'mango', 'canteloupe', 'guava', 'pineapple', 'coconut', 'pear']

In [187]:
fruit_list.sort() # Sorting list in-place
print('After sorting: fruit_list = %s' % fruit_list)

After sorting: fruit_list = ['apple', 'banana', 'canteloupe', 'coconut', 'guava', 'mango', 'pear', 'pineapple']

In [188]:
animal_list = ['dog', 'cat', 'frog']
print(animal_list)
animal_list.extend("pig")
# Notice the difference between ["pig"] and "pig" as an argument to list.extend
print(animal_list)

['dog', 'cat', 'frog']
['dog', 'cat', 'frog', 'p', 'i', 'g']

In [189]:
# Remove items either by index, by slice, or by value
del animal_list[-3:]
print(animal_list)

['dog', 'cat', 'frog']

In [190]:
animal_list.append('pig')
animal_list

['dog', 'cat', 'frog', 'pig']

In [191]:
# You can insert into the middle of lists also, 
# but less efficiently O(n)
animal_list.insert(2, 'horse')
print(animal_list)

['dog', 'cat', 'horse', 'frog', 'pig']

In [192]:
# Removing list elements by value
animal_list.remove('cat')
print(animal_list)

['dog', 'horse', 'frog', 'pig']

In [193]:
# Removing list elements that are not present: raises exception ValueError
animal_list.remove('gopher')
print(animal_list)

ValueError: list.remove(x): x not in list

In [194]:
# Concatenating lists using the addition (+) operator
print(animal_list)
animal_list = ['bat'] + animal_list
print(animal_list)
animal_list += ['dingo']
print(animal_list)

['dog', 'horse', 'frog', 'pig']
['bat', 'dog', 'horse', 'frog', 'pig']
['bat', 'dog', 'horse', 'frog', 'pig', 'dingo']

In [195]:
# Decompose elements into parallel lists
dates = ["09/05/1984", "05/04/1999", "01/02/1921"]
months, days, years = [], [], []
for date in dates:
    mm, dd, yyyy = date.split('/') # Use tuple-unpacking to extract substrings
    months.append(int(mm))
    days.append(int(dd))
    years.append(int(yyyy))
    print('months=%s, days=%s, years=%s' % (months, days, years))

months=[9], days=[5], years=[1984]
months=[9, 5], days=[5, 4], years=[1984, 1999]
months=[9, 5, 1], days=[5, 4, 2], years=[1984, 1999, 1921]

In [196]:
print(animal_list)
animals2 = animal_list
animals2[3] = 'donkey'
print(animal_list)

['bat', 'dog', 'horse', 'frog', 'pig', 'dingo']
['bat', 'dog', 'horse', 'donkey', 'pig', 'dingo']

In [197]:
backup = animal_list[:]   # Same result as `animal_list.copy()`
print('Initially: animal_list=%s' % animal_list)
print('Popped value:', backup.pop(0))
print('After pop: backup=%s' % backup)
print('After pop: animal_list=%s' % animal_list)

Initially: animal_list=['bat', 'dog', 'horse', 'donkey', 'pig', 'dingo']
Popped value: bat
After pop: backup=['dog', 'horse', 'donkey', 'pig', 'dingo']
After pop: animal_list=['bat', 'dog', 'horse', 'donkey', 'pig', 'dingo']

In [198]:
list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [199]:
# Oops! We still changed original after modifying copying
lol2 = list_of_lists.copy()
lol2[1].append(55)
lol2.append([11, 12, 13])
print("Original:    ", list_of_lists)
print("Shallow copy:", lol2)

Original:     [[1, 2, 3], [4, 5, 6, 55], [7, 8, 9]]
Shallow copy: [[1, 2, 3], [4, 5, 6, 55], [7, 8, 9], [11, 12, 13]]

In [200]:
from copy import deepcopy
list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]
lol3 = deepcopy(list_of_lists)
lol3[1].extend([55, 66, 77])
print("Original: ", list_of_lists)
print("Deep copy:", lol3)

Original:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Deep copy: [[1, 2, 3], [4, 5, 6, 55, 66, 77], [7, 8, 9]]

In [202]:

# Reversing (by mutation)
animal_list.reverse()
print(animal_list)

['dingo', 'pig', 'donkey', 'horse', 'dog', 'bat']

In [203]:
# Reversing (and returning result)
reverse_animal_list = reversed(animal_list)
print(animal_list)
print(reverse_animal_list)

['dingo', 'pig', 'donkey', 'horse', 'dog', 'bat']
<list_reverseiterator object at 0x104a915c0>

In [204]:
# That was strange! Python 3 is often "lazy" and doesn't 
# compute something until needed
# Cast iterable to list to make printing explict
print(list(reverse_animal_list))

['bat', 'dog', 'horse', 'donkey', 'pig', 'dingo']

In [205]:
# Pretend `animal_list` is a billion item list (where a copy would eat memory)
reverse_animal_list = reversed(animal_list)  
for item in reverse_animal_list:
    print(item)

bat
dog
horse
donkey
pig
dingo

In [206]:
# Sorting (by mutation, in-place)
animals = animal_list[:]
animals.sort()
print(animal_list)
print(animals)

['dingo', 'pig', 'donkey', 'horse', 'dog', 'bat']
['bat', 'dingo', 'dog', 'donkey', 'horse', 'pig']

In [207]:
# Another gotcha! Not all elements can be compared to be sorted
animals.insert(2, None)
print(animals)
animals.sort()
print(animals)

['bat', 'dingo', None, 'dog', 'donkey', 'horse', 'pig']

TypeError: unorderable types: NoneType() < str()

In [208]:
# We can use a custom sort key function
def my_key(x):
    return "" if x is None else x
    
animals.sort(key=my_key)
animals

[None, 'bat', 'dingo', 'dog', 'donkey', 'horse', 'pig']

In [209]:
# But it still won't sort on *everything*
animals.append(1+1j)
animals.sort(key=my_key)

TypeError: unorderable types: complex() < str()

In [218]:
# Loop over a collection of similar items
class Oddthing(object):
    def split(self):
        return 'Thomas', 'Bayes'
    
name_list = ["Rene Descartes", "Marie Sophie Germain", "Leonhard Euler", 
             "Ada Lovelace", "Isaac Newton", "Georg Cantor", Oddthing()]

for name in name_list:
    *first, last = name.split()
    print(first[-1].lower(), last.upper())

rene DESCARTES
sophie GERMAIN
leonhard EULER
ada LOVELACE
isaac NEWTON
georg CANTOR
thomas BAYES

In [213]:
# A C programming veteran's first Python loop using explicit index
name_list = ["Rene Descartes", "Marie Sophie Germain", "Leonhard Euler", 
             "Ada Lovelace", "Isaac Newton", "Georg Cantor"]
count = 0
for k in range(len(name_list)):
    print(k, name_list[k])
    if ('r' in name_list[k]):
        count += 1 # equivalent to count = count + 1
print("The value of count is %d" % count)

0 Rene Descartes
1 Marie Sophie Germain
2 Leonhard Euler
3 Ada Lovelace
4 Isaac Newton
5 Georg Cantor
The value of count is 4

In [220]:
# "Pythonic" loop without explicit index
name_list = ["Rene Descartes", "Marie Sophie Germain", "Leonhard Euler", 
             "Ada Lovelace", "Isaac Newton", "Georg Cantor"]
count = 0
for name in name_list:
    print(name)
    count += 'r' in name
print("The value of count is %d" % count)

Rene Descartes
Marie Sophie Germain
Leonhard Euler
Ada Lovelace
Isaac Newton
Georg Cantor
The value of count is 4

In [221]:
# Returns list containing first characters of each word in the list mylist
[name[0] for name in name_list]

['R', 'M', 'L', 'A', 'I', 'G']

In [222]:
[name for name in name_list if 'r' in name] # List of "names with r" counted above

['Rene Descartes', 'Marie Sophie Germain', 'Leonhard Euler', 'Georg Cantor']

In [223]:
# Sometimes we genuinely do want both an index and an item
for k, name in enumerate(name_list):
    print("(%d) %s" % (k, name))

(0) Rene Descartes
(1) Marie Sophie Germain
(2) Leonhard Euler
(3) Ada Lovelace
(4) Isaac Newton
(5) Georg Cantor

### Dict type

ধরা যাক, আমাদের কোডটা এমন

In [226]:
fruits = ['Mango', 'Apple', 'Grape', 'Orange']
Quantitiy = [5, 11, 34, 121]
price = [396.85,  545.79, 914.49, 169.67]
for k in range(4):
    value = Quantitiy[k] * price[k]
    print('The price of %s with %d quantity is %10.2f.' % (fruits[k], Quantitiy[k], value))

The price of Mango with 5 quantity is    1984.25.
The price of Apple with 11 quantity is    6003.69.
The price of Grape with 34 quantity is   31092.66.
The price of Orange with 121 quantity is   20530.07.

এখন যদি আমরা নতুন করে আরো fruits যোগ করতে চাই, তাহলে Quantitiy এবং price list এও আমাদের ঐ রকম এলাইন করে ভ্যালু যোগ করা লাগবে। ছোট list এর জন্য হয়তো ওত সমস্যা হবে না কিন্তু list এর আকার যত বড় হবে, এইটারে ম্যানেজ করা কিন্তু সমস্যা ছাড়া অন্য কিছু হবে না। তাইলে অবশ্যই একটা ভালো স্মার্ট কিছু থাকা উচিত list এ ।

In [227]:
stocks = [ {'fruits':'Mango', 'quantity':267, 'price':396.85},
           {'fruits':'Apple', 'quantity':349, 'price':549.79},
           {'fruits':'Grape', 'quantity':123, 'price':914.49},
           {'fruits':'Orange', 'quantity':181, 'price':169.67}
         ]
for stock in stocks:
    value = stock['quantity'] * stock['price']
    print('The value of %d %s fruits is %10.2f.' % (
                        stock['quantity'], stock['fruits'], value))

The value of 267 Mango fruits is  105958.95.
The value of 349 Apple fruits is  191876.71.
The value of 123 Grape fruits is  112482.27.
The value of 181 Orange fruits is   30710.27.

বৈশিষ্ট্যঃ 
<ul>

  <li>কমা সেপারেটেড key: value pairs</li>
  <li> সাধারণত"{}" দিয়ে আটকানো</li>
  <li>heterogeneous</li>
  <li>mutable</li>
      <li>dict typer এর সাথ tuple এবং lists এর মধ্যে পার্থক্য হইলো, value access করার key-গুলা string টাইপ হয়  </li>
</ul>

In [229]:
empty_dict = {}
print('empty_dict has type %s.' % type(empty_dict))

empty_dict has type <class 'dict'>.

In [230]:
fruits = {'fruit':'Mango', 'quantity':267, 'price':396.85}
print(fruits)

{'fruit': 'Mango', 'quantity': 267, 'price': 396.85}

In [232]:
print(fruits['fruit'])

Mango

In [238]:
for key in fruits:
    print(key+":"+ str(fruits[key]))

fruit:Mango
quantity:267
price:396.85

#### Dictionaries মেথডঃ 
<ul>
<li>clear</li>
<li>copy</li>
<li>fromkeys</li>
<li>get</li>
<li>items</li>
<li>keys</li>
<li>pop</li>
<li>popitem</li>
<li>setdefault</li>
<li>update</li>

</ul>

In [239]:
for key in fruits:
    print(key)

fruit
quantity
price

In [241]:
fruits['available']

KeyError: 'available'

In [242]:
fruits.get('available','yes')

'yes'

In [245]:
print(fruits.get('home-delivery','No'))

No

In [247]:
print(fruits['home-delivery'])

KeyError: 'home-delivery'

In [252]:
print("Before : %s" %fruits)

Before : {'fruit': 'Mango', 'quantity': 267, 'price': 396.85}

In [253]:
fruits['origin'] = "Rajshahi"

In [254]:
print("after %s" %fruits)

after {'origin': 'Rajshahi', 'fruit': 'Mango', 'quantity': 267, 'price': 396.85}

In [255]:
fruits['price'] = 423.02
print('Update %s' %fruits)

Update {'origin': 'Rajshahi', 'fruit': 'Mango', 'quantity': 267, 'price': 423.02}

In [256]:
del fruits['origin']
print('After %s' %fruits)

After {'fruit': 'Mango', 'quantity': 267, 'price': 423.02}

In [260]:
fruits.update({'fruit':'Apple', 'quantity':349, 'price':549.79, 'origin':'southe africa'})
fruits

{'fruit': 'Apple', 'origin': 'southe africa', 'price': 549.79, 'quantity': 349}

In [261]:
'price' in fruits

True

#### set 

set, dicttionaries type এর মতোই কিন্তু শুধু keys আছে, কোন ভ্যালু নাই।

In [262]:
instructors = {"Farhad Naeem", "Faria nishita"}
instructors.add("Donald Duck")
print(instructors)
instructors.add("Daniel Craig")
instructors

{'Faria nishita', 'Farhad Naeem', 'Donald Duck'}

{'Daniel Craig', 'Donald Duck', 'Farhad Naeem', 'Faria nishita'}

In [268]:
list_of_Fs = ["Faru", "Fari", "Fatu"]
names_with_F = set(list_of_Fs)
names_with_F.add("Farhad Naeem")
names_with_F | instructors

{'Daniel Craig',
 'Donald Duck',
 'Farhad Naeem',
 'Fari',
 'Faria nishita',
 'Faru',
 'Fatu'}

In [269]:
names_with_F & instructors

{'Farhad Naeem'}

In [270]:
names_with_F ^ instructors

{'Daniel Craig', 'Donald Duck', 'Fari', 'Faria nishita', 'Faru', 'Fatu'}

In [271]:
names_with_F - instructors

{'Fari', 'Faru', 'Fatu'}

In [272]:
names_with_F

{'Farhad Naeem', 'Fari', 'Faru', 'Fatu'}

In [273]:
names_with_F <= instructors

False

In [274]:
names_with_F.add("Ferdous")

In [275]:
names_with_F

{'Farhad Naeem', 'Fari', 'Faru', 'Fatu', 'Ferdous'}

In [276]:
names_with_F.remove("Ferdous")

In [277]:
names_with_F

{'Farhad Naeem', 'Fari', 'Faru', 'Fatu'}

In [279]:
{x for x in (instructors | names_with_F) if 'Fa' in x}

{'Farhad Naeem', 'Fari', 'Faria nishita', 'Faru', 'Fatu'}

## Data types from the Python Standard Library